# Generated by Django 4.2.4 on 2023-08-20 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otpcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otpcode',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
