# Generated by Django 4.2.4 on 2023-09-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_phone_number_otpcode_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='phone',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
