# Generated by Django 4.2.4 on 2023-09-08 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_products_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('name',), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
